from cola import ColaPrioridad
from paciente import Paciente

paciente = Paciente("Daniel", "Me dio un derrame")
paciente2 = Paciente("Migue", "Tengo gripa")
paciente3 = Paciente("Pablo", "Vengo para control")
paciente4 = Paciente("Juan", "Tengo tos")
paciente5 = Paciente("Jeronimo", "Sufrio una fractura")
paciente6 = Paciente("Felipe", "Sufiro un infarto")

print("-------------------------------")
print(paciente.prioridad)
print(paciente2.prioridad)
print(paciente3.prioridad)
print(paciente4.prioridad)
print(paciente5.prioridad)
print(paciente6.prioridad)
print("-------------------------------")
fila = ColaPrioridad()
fila.insertar(paciente3)
fila.insertar(paciente4)
fila.insertar(paciente2)
fila.insertar(paciente6)
fila.insertar(paciente)
fila.mostrar()
fila.atender()
fila.mostrar()
fila.atender()
fila.atender()
fila.mostrar()
fila.atender()
fila.atender()
fila.atender()
